### ISSUE TITLE
Extremely high number of 404 returned by Chrome subscriptions (FCM endpoints)

### ISSUE THREAD

**Issue by collimarco** [pushpad/web-push#14]
Starting from Jun 26 we noticed a very high number of Chrome subscriptions (`https://fcm.googleapis.com/fcm/send/...`) returning 404 errors. All these subscriptions were returning successful status codes in the previous days / months.

This gem then raises `InvalidSubscription` when a 404 is returned by the endpoint.

This seems like a serious issue in FCM...

I am opening this topic here in case someone is experiencing the same problem or has additional information to share.

**Comment by collimarco** [comment]
I have also opened an issue in the Chromium bug tracker:

https://issues.chromium.org/issues/349646659

**Comment by collimarco** [comment]
This is the exact response (from logs):

```
404 Not Found

A valid push subscription endpoint should be specified in the URL as such: https://fcm.googleapis.com/wp/dHIoDxE7Hdg:APA91bH1Zj0kNa...
```

Note: the endpoint in the response is not the real FCM endpoint, it seems to be just an example.

**Comment by welishr** [comment]
Hi this is an intended change where the [stale](https://firebase.google.com/docs/cloud-messaging/manage-tokens#stale-and-expired-tokens) tokens for devices, which have not been connected to FCM in over 270 days, will be considered as expired and invalid. If a request is sent to an invalid token, it will be rejected with a 404 error.  

Messages sent to these tokens previously were accepted and then never delivered (because the target devices are inactive), FCM now responds with a 404 instead. We have verified that we have seen no change in our delivery rates over the last week, despite the increase in 404s returned

**Comment by collimarco** [comment]
@welishr Thanks for the information.

However some of our customers are complaining that they are also seeing a lower number of clicks. So this suggests that many valid subscriptions were also removed...

> I see that since this change thee total no. of clicks has dropped from 24k/day to around 14k/day. So it is likely that these contained a lot of valid subscriptions too. 
> [number of notifications successfully sent on the left, number of clicks on the right]

![1000000676](https://github.com/pushpad/web-push/assets/90962/2edfd56e-0b92-47ac-abb2-442da26d4ad7)

**This is a serious damage for us and for our customers.** 

**Please inspect this issue and consider restoring all the subscriptions.**
